steps:
  - name: 'node:18'
    dir: 'frontend'
    entrypoint: npm
    args: ['install']

  - name: 'node:18'
    dir: 'frontend'
    entrypoint: npm
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'frontend'
    entrypoint: gcloud
    args:
      [
        'app',
        'deploy',
        'app.yaml',
        '--quiet'
      ]

options:
  logging: CLOUD_LOGGING_ONLY