steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'backend/Dockerfile',
        '-t',
        'gcr.io/$PROJECT_ID/laundry-backend',
        'backend'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/laundry-backend'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'laundry-backend',
        '--image',
        'gcr.io/$PROJECT_ID/laundry-backend',
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/laundry-backend'

options:
  logging: CLOUD_LOGGING_ONLY